import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Joseph Fantuzzi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}></nav>
      <main>
        <p>Hello, I&apos;m</p>
        <h1>Joseph Fantuzzi</h1>
        <p>Full Stack Web Developer | Software Engineer</p>
      </main>
    </div>
  );
}
